export enum ReportReason {
    BREAKES_RULES = 'BREAKES_RULES',
    HARASSMENT = 'HARASSMENT',
    HATE = 'HATE',
    SHARING_PERSONAL_INFORMATION = 'SHARING_PERSONAL_INFORMATION',
    IMPERSONATION = 'IMPERSONATION',
    COPYRIGHT_VIOLATION = 'COPYRIGHT_VIOLATION',
    TRADEMARK_VIOLATION = 'TRADEMARK_VIOLATION',
    SPAM = 'SPAM',
    SELF_HARM_OR_SUICIDE = 'SELF_HARM_OR_SUICIDE',
    OTHER = 'OTHER'
  }
  